### ISSUE TITLE
Exit Intent not Popping up on Firefox or Safari Desktop

### ISSUE THREAD

**Issue by adrileo3** [daltonmenezes/use-exit-intent#1]
Hi @daltonmenezes,

I tried testing on Firefox and Safari and the popup doesn't happen, is this the case on your end?

**Comment by daltonmenezes** [comment]
Hi @adrileo3 , thanks for letting me know. Could you please check the v1.0.6?

**Comment by adrileo3** [comment]
Hi @daltonmenezes , its fixed now, thank you!
