### ISSUE TITLE
Support for the experimental syntax 'optionalChaining' isn't currently enabled

### ISSUE THREAD

**Issue by baybomax** [daltonmenezes/use-exit-intent#3]
Support for the experimental syntax 'optionalChaining' isn't currently enabled

**Comment by daltonmenezes** [comment]
Hi @baybomax , could you please provide more info on this?

Are you using CRA or Storybook?
How are you trying to handle useExitIntent and what errors did you get with it?

This seems to me something related to babel and not a useExitIntent thing. 🤔
