### ISSUE TITLE
FR: don't repeatedly interrupt users

### ISSUE THREAD

**Issue by aa-jeremyhoover** [daltonmenezes/use-exit-intent#6]
@daltonmenezes First off, great work on this library! Docs are amazing and it works as expected 🔥🔥🔥

I would like to prevent users from seeing the same exit intent content twice if they have explicitly closed out of the content. I see you have `unsubscribe()`, but that looks like it's intended for a site-wide use rather than per instance. I plan to add this feature to my app, would this be useful to have in the library itself?

Thanks!

**Comment by daltonmenezes** [comment]
Hi @aa-jeremyhoover , thanks and sorry for the delay! Sure, it would be awesome to have this feature! A PR will be appreciated!

**Comment by aa-jeremyhoover** [comment]
Closing because I didn't realize that this already exists by just setting a different `cookie: { key }` out of the box. 🤦 .
